DELETE [dbo].[DIM_COUNTRIES]
DELETE [dbo].[DIM_MEMBERS]
DELETE [dbo].[DIM_PLANS]
DELETE [dbo].[DIM_PRODUCT]
DELETE [dbo].[FACT_ORDERS]
DELETE [dbo].[FACT_REVIEWS]
DELETE [dbo].[SUMMARY_ORDERS]

DROP PROCEDURE ETL_COUNTRIES
DROP PROCEDURE ETL_MEMBERS
DROP PROCEDURE ETL_PRODUCTS
DROP PROCEDURE ETL_PLANS
DROP PROCEDURE ETL_ORDERS
DROP PROCEDURE ETL_SUMMARY_ORDERS
DROP PROCEDURE ETL_REVIEWS
DROP PROCEDURE ETL_MASTER

CREATE PROCEDURE ETL_COUNTRIES AS
BEGIN

	INSERT INTO DIM_COUNTRIES
	SELECT	C.country, C.population, C.high_education, C.HDI_rank
	FROM [BI_project].[dbo].[COUNTRIES] AS C
	WHERE C.country NOT IN (SELECT DC.DIM_COUNTRY FROM DIM_COUNTRIES AS DC)

END



CREATE PROCEDURE ETL_MEMBERS AS
BEGIN

	INSERT INTO DIM_MEMBERS
	SELECT M.Username, M.Country, M.Member_Since, M.occupation, M.personal_website, M.avg_response_time, M.language, M.certification, M.skill, M.education
	FROM [BI_project].dbo.MEMBERS AS M
	WHERE M.Username NOT IN (SELECT DM.DIM_MEMBER FROM DIM_MEMBERS AS DM)

END



CREATE PROCEDURE ETL_PRODUCTS AS
BEGIN

	INSERT INTO DIM_PRODUCT
	SELECT P.Product_ID, P.Name,P.Description, P.Supplier, P.category, P.[Dealing_Protocol]
	FROM BI_project.[dbo].[PRODUCTS] AS P
	WHERE P.[Product_ID] NOT IN (SELECT DP.DIM_PRODUCT FROM DIM_PRODUCT AS DP)

END




CREATE PROCEDURE ETL_PLANS AS
BEGIN

	INSERT INTO DIM_PLANS
	SELECT P.Product_ID, P.type, P.name, P.delivery_time, P.revisions_limit, P.content, P.Price, P.lesson_time
	FROM BI_project.dbo.PLANS AS P
	WHERE P.Product_ID NOT IN (SELECT DP.DIM_PRODUCT FROM DIM_PLANS AS DP)

END





CREATE PROCEDURE  ETL_ORDERS AS
BEGIN

	INSERT INTO FACT_ORDERS
	SELECT O.orderID,
		   o.[D/T],
		   (SELECT M.DIM_COUNTRY FROM DIM_MEMBERS AS M WHERE M.DIM_MEMBER IN (SELECT DP.DIM_MEMBER 
																		FROM DIM_PRODUCT AS DP WHERE DP.DIM_PRODUCT = O.Product_ID)),
			(SELECT DP.DIM_MEMBER FROM DIM_PRODUCT AS DP WHERE DP.DIM_PRODUCT = O.Product_ID),
			O.Product_ID,
			O.type,

			O.username,

			(SELECT P.PRICE*(1-O.SERVICE_FEE) FROM DIM_PLANS AS P WHERE O.Product_ID = P.DIM_PRODUCT AND O.type = P.DIM_PLAN),
			(SELECT P.PRICE*(O.SERVICE_FEE) FROM DIM_PLANS AS P WHERE O.Product_ID = P.DIM_PRODUCT AND O.type = P.DIM_PLAN),

			O.actual_revisions / (SELECT CAST(P.[revisions_limit] AS decimal) FROM DIM_PLANS AS P WHERE O.Product_ID = P.DIM_PRODUCT AND O.type = P.DIM_PLAN),

			(SELECT P.[delivery_time] - O.[actual_delivery_time] FROM DIM_PLANS AS P WHERE O.Product_ID = P.DIM_PRODUCT AND O.type = P.DIM_PLAN),

			O.service_fee,

			O.satisfaction

	FROM BI_project.dbo.ORDERS AS O

	WHERE O.orderID NOT IN (SELECT FO.PKorders FROM FACT_ORDERS AS FO)
	
END



CREATE PROCEDURE ETL_REVIEWS AS
BEGIN
		--for products--
	INSERT INTO FACT_REVIEWS 
	SELECT PR.[D/T],
			 (SELECT M.DIM_COUNTRY FROM DIM_MEMBERS AS M JOIN DIM_PRODUCT AS P ON P.DIM_MEMBER = M.DIM_MEMBER WHERE P.DIM_PRODUCT = PR.Product_ID),

			 (SELECT P.DIM_MEMBER FROM DIM_PRODUCT AS P WHERE P.DIM_PRODUCT = PR.Product_ID),

			 PR.Product_ID,

			 PR.writer,

			 PR.[Star Rating],

			 PR.[Helpful Rating]

	FROM BI_project.dbo.[PRODUCTS REVIEWS] AS PR

	--FOR FREELANCERS--
	INSERT INTO FACT_REVIEWS
	SELECT FR.[D/T],

			 (SELECT M.DIM_COUNTRY FROM DIM_MEMBERS AS M WHERE M.DIM_MEMBER = FR.freelancer),

			 FR.freelancer,

			 '-1',

			 FR.writer,

			 FR.[star_rating],

			 FR.[Helpful_Rating]

	FROM BI_project.dbo.[FREELANCERS REVIEWS] AS FR

END


CREATE PROCEDURE ETL_SUMMARY_ORDERS AS
BEGIN
	
	INSERT INTO SUMMARY_ORDERS
	SELECT FO.DIM_DATE,
			FO.DIM_COUNTRY,
			FO.DIM_SELLER,
			FO.DIM_PRODUCT,

			SUM(FO.[company_income]),

			SUM(FO.[seller_income]),

			COUNT(*),

			SUM(CASE WHEN FO.difference_delivery_time < 0 THEN 1 ELSE 0 END),

			SUM(CASE WHEN FO.difference_delivery_time < 0 THEN 1 ELSE 0 END)/COUNT(*),

			AVG(FO.ratio_revisions),

			AVG(FO.satisfaction),

			(SELECT AVG(FR.star_rating) FROM FACT_REVIEWS AS FR WHERE FR.DIM_PRODUCT = FO.DIM_PRODUCT),

			(SELECT AVG(FR.star_rating) FROM FACT_REVIEWS AS FR WHERE FR.DIM_PRODUCT = '-1' AND FR.DIM_FREELANCER = FO.DIM_SELLER)

	FROM FACT_ORDERS AS FO

	GROUP BY FO.DIM_DATE, FO.DIM_COUNTRY, FO.DIM_SELLER, FO.DIM_PRODUCT

END

CREATE PROCEDURE ETL_MASTER AS 
BEGIN
	EXEC ETL_COUNTRIES
	EXEC ETL_MEMBERS
	EXEC ETL_PRODUCTS
	EXEC ETL_PLANS
	EXEC ETL_ORDERS
	EXEC ETL_REVIEWS
	EXEC ETL_SUMMARY_ORDERS
END

EXEC ETL_MASTER